uint8 GPS=0
uint8 METER=1
uint8 GNSS_ONLY=0
uint8 ARUCO_POST=1
uint8 OBJECT=2
uint8 LOCAL=3
string target_id
float64 lat
float64 lon
float64 x_m
float64 y_m
uint8 goal_type
uint8 target_type
float64 tolerance_m
bool is_return
---
bool success
string message
---
float64 distance_to_goal_m
float64 cross_track_error_m
string state
