teleop_twist_joy:
  ros__parameters:
    enable_button: 0

    axis_linear.x: 1
    axis_linear.y: 2
    axis_linear.z: -1

    scale_linear.x: 1.27
    scale_linear.y: 0.0
    scale_linear.z: 0.0

    axis_angular.yaw: 0
    axis_angular.pitch: -1
    axis_angular.roll: -1

    scale_angular.yaw: 0.5
    scale_angular.pitch: 0.0
    scale_angular.roll: 0.0
    publish_stamped_twist: true
