### ekf_local: Fuses odometry and IMU for odom->base_link
ekf_filter_node_odom:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false
    publish_tf: true
    publish_acceleration: false
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /ackermann_steering_controller/odometry
    odom0_config: [true, true, true,
                   false, false, false,
                   true, true, true,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10
    odom0_nodelay: true
    odom0_differential: false
    odom0_relative: false

    imu0: /imu
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_nodelay: false
    imu0_differential: false
    imu0_relative: false
    use_control: false

### ekf_global: Fuses odometry, IMU, and GPS for map->odom
ekf_filter_node_map:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false
    publish_tf: true
    publish_acceleration: false
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    odom0: /ackermann_steering_controller/odometry
    odom0_config: [true, true, true,
                   false, false, false,
                   true, true, true,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10
    odom0_nodelay: true
    odom0_differential: false
    odom0_relative: false

    imu0: /imu
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_nodelay: false
    imu0_differential: false
    imu0_relative: false

    odom1: /odometry/gps
    odom1_config: [true,  true,  false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom1_queue_size: 10
    odom1_nodelay: true
    odom1_differential: false
    odom1_relative: false

### navsat_transform: Converts GPS to odometry message
navsat_transform_node:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: 0.0
    yaw_offset: 1.5707963
    zero_altitude: true
    broadcast_cartesian_transform: false
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: true
    gps_frame: navsat
    datum: [38.42391162772634, -110.78490558433397, 0.0]
